Fix helm init due to syntax error
Following the
```
$ kubectl plugin helm init
./helm: line 61: syntax error near unexpected token `}'
error: exit status 2
```